<p><a href="/nl_BE/pagina/producten">Ga naar producten</a></p>


<!-- tweed werkt zonder routes -->
<p><a href="<?php echo $this->url(array('controller' =>'page',
        'action' => 'index',
    'params' => array('slug' => 'producten' , 'lang' => 'nl_BE')
        )); ?>">Ga naar producten</a></p>


<!-- derde is de beste manier,  als de route -->
<p><a href="<?php echo $this->url(array('slug' => 'producten',
        'lang' => 'nl_BE'), 'page'); ?>">Ga naar producten</a></p>
